version: "3.8"

services:
  postgresdb:
    image: postgres:15-alpine
    container_name: meter-postgres
    restart: always
    environment:
      POSTGRES_DB: meterbilldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/MeterBillGenerator
      dockerfile: Dockerfile
    container_name: meter-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/meterbilldb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgresdb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: meter-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
