## PostgreSQL Configuration using Environment Variables for Render
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/meterbilldb}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## Hibernate Settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
## HTTP Session Cookie Configuration for Cross-Origin Deployment
#server.servlet.session.cookie.same-site=lax
#server.servlet.session.cookie.http-only=true


spring.datasource.url=jdbc:postgresql://localhost:5432/meterbilldb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect